# Generated by Django 5.2 on 2026-03-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userprofile_role_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Where Every Meal Is A Celebration', max_length=255)),
                ('subtitle', models.CharField(default='Our Heritage', help_text='Small eyebrow text', max_length=100)),
                ('description', models.TextField(help_text='Main description text')),
                ('quote', models.TextField(help_text='Featured quote')),
                ('vision_title', models.CharField(default='Vision', max_length=100)),
                ('vision_body', models.TextField(help_text='Vision card content')),
                ('cuisine_title', models.CharField(default='Cuisine', max_length=100)),
                ('cuisine_body', models.TextField(help_text='Cuisine card content')),
                ('service_title', models.CharField(default='Service', max_length=100)),
                ('service_body', models.TextField(help_text='Service card content')),
                ('years_serving', models.CharField(default='12+', help_text='Years serving stat', max_length=20)),
                ('menu_items', models.CharField(default='80+', help_text='Menu items stat', max_length=20)),
                ('rating', models.CharField(default='4.9★', help_text='Rating stat', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('description', models.CharField(blank=True, help_text='Description shown on hover', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (0-5, max 6 images)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this image in gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
