# Generated by Codex on 2026-03-14

from django.db import migrations, models


def seed_aboutus_relations(apps, schema_editor):
    AboutUs = apps.get_model("api", "AboutUs")
    GalleryImage = apps.get_model("api", "GalleryImage")
    StaffMember = apps.get_model("api", "StaffMember")

    about, _ = AboutUs.objects.get_or_create(
        id=1,
        defaults={
            "title": "Where Every Meal Is A Celebration",
            "subtitle": "Our Heritage",
            "description": "Near Simso Filling Station in Luwinga, we serve premium dishes in a warm family-restaurant setting.",
            "quote": "Good food is the foundation of genuine happiness - we serve both.",
            "vision_title": "Vision",
            "vision_body": "Build a modern Malawian dining brand where consistency, comfort, and quality define every table.",
            "cuisine_title": "Cuisine",
            "cuisine_body": "Local favorites and signature mains from chambo to goat dishes, with curated snacks and beverages.",
            "service_title": "Service",
            "service_body": "Fast reservations, smooth checkout, and attentive hosting for both casual and formal dining moments.",
            "years_serving": "12+",
            "menu_items": "80+",
            "rating": "4.9★",
        },
    )

    GalleryImage.objects.filter(about_us__isnull=True).update(about_us=about)
    StaffMember.objects.filter(about_us__isnull=True).update(about_us=about)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_gallery_aboutus"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="about_image",
            field=models.ImageField(blank=True, null=True, upload_to="about/"),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="about_us",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="gallery_images",
                to="api.aboutus",
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="about_us",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="team_members",
                to="api.aboutus",
            ),
        ),
        migrations.RunPython(seed_aboutus_relations, migrations.RunPython.noop),
    ]

