# Generated by Codex on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_aboutus_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="title",
            field=models.CharField(blank=True, help_text="Image title shown on hover", max_length=120),
        ),
    ]

