# Generated by Codex on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_gallery_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "about_us",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="services",
                        to="api.aboutus",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Service",
                "verbose_name_plural": "About Services",
                "ordering": ["order", "id"],
            },
        ),
    ]

