# Generated by Django 5.2 on 2026-03-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_seed_gallery_images_retry'),
        ('api', '0022_menu_item_region_cleanup'),
    ]

    operations = [
    ]
